### ISSUE TITLE
draw_normal_icc does not preserve variance

### ISSUE THREAD

**Issue by chadhazlett** [DeclareDesign/fabricatr#111]
Suggesting that the output from draw_normal_icc be rescaled to have same variance as it would have with ICC=0. Simply rescaling the result preserves the ICC as well so seems like a reasonable solution.

**Comment by nfultz** [comment]
Right now, we require the distribution to be specified in two of {ICC, within var, between var}. I think it would be a nice feature to allow total var also. This could be done up front, rather than rescaling output at the end.  

```r
> x1 <- draw_normal_icc(clusters = clusters, ICC = 0.5)
> tapply(x1, clusters, var)
           1            2            3            4            5 
1.0199539093 1.0676476570 1.0023143801 0.9407772395 1.0030194267 
> var(x1)
[1] 2.551552451
> x2 <- draw_normal_icc(clusters = clusters, ICC = 0)
Error in draw_normal_icc(clusters = clusters, ICC = 0) : 
  An `ICC` of 0 with a finite within-cluster variance implies zero between-cluster variance. You can generate data with zero ICC using R's standard `rnorm` command to generate normal data independent of the cluster variable.
> x2 <- draw_normal_icc(clusters = clusters, ICC = 0.01)
> tapply(x2, clusters, var)
           1            2            3            4            5 
0.9342094979 1.0343334146 0.9968004618 1.0099807607 1.0361599501 
> var(x2)
[1] 1.014854816
```

Desired behavior is something like:

```
> x3 <- draw_normal_icc(clusters = clusters, ICC = 0.5, total_sd=1)
> var(x3)
[1] 1.00
```

**Comment by aaronrudkin** [comment]
This was just committed. There will be an additional argument called `total_sd`. `total_sd` must be used with `ICC` and cannot be used with `sd` or `sd_between`. I just did a rescale of the resulting variable if `total_sd` is provided (generate variable -> standardize -> scale with new sd -> re-add mean). Note that because of the nature of the process, this variable is by construction exact while `sd`, `sd_between`, and `ICC` are all stochastic.

It is probably possible to loosen the constraints; I briefly looked at the math for mixture of Gaussians to see which total_sd is implied by the `sd`, `sd_between`, and `ICC` conditions but decided to implement it as-is first. If someone wants to take a swing at the math on this feel free to open a new issue or re-open this one, I'll consider the solved.

(There are also tests for all these cases).
