### ISSUE TITLE
group_by() %>% mutate functionality

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#119]
Right now, at the lowest level the data set you have access to is the full dataset - if upper level is 5 and lower level is 3 each, your dataset is 15 long. This is fine for many applications, but if you want to create the variable within each upper level unit (if it's schools within states, you may want to draw some school-level variable within each state and then append). This is like a group_by %>% mutate %>% ungroup. We need the same thing. 

The other oddity currently is that N means something different than I'd understood. If you have:

```
fabricate(
  states = add_level(N = 5),
  schools = add_level(
    N = 3,
    school_var = rnorm(N))
)
```

the N in `rnorm` is equal to 15, not 3, as just declared. If we keep this as is, we need to make that very clear. I find it confusing.

**Comment by nfultz** [comment]
This goes back to add_level not actually beng a split apply combine

**Comment by aaronrudkin** [comment]
It's clear we've hit a few issues with this in general. I'm not sure what the full solution is -- you could imagine some wrapper like `block()` or something that tells it to allocate the internal variables per block rather than across the whole dataset. I think we should definitely come up with an answer, whether in documentation, functionality, or both to accommodate this.

It's unclear to me in your example what the intended behaviour is; how many unique values of school_var would you expect to be generated? Are you expecting 3 school vars, which are duplicated across every state? Given the relative simplicity of the example if you could mock up a base R / dplyr / whatever version of the example as it is intended to be executed that would help me parse it.

**Comment by aaronrudkin** [comment]
Tagging in #79 here, which was a similar request to this kind of sensitivity to be able to directly modify higher-level variables with awareness of lower level block membership. It's not exactly the same as group_by (which also includes generating variables in chunks by block) but it overlaps. Tagging so we have a reference as we continue on this issue.

**Comment by nfultz** [comment]
This is done.
