### ISSUE TITLE
duplicated var names across levels

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#13]
This replaces the var if the names are duplicated:

```
fabricate(
    cities = level(N = 2, elevation = runif(n = N)),
    citizens = level(N = 2, elevation = runif(n = N)),
  )
```

This, because you're going back to a higher level, does not:

```
fabricate(
    cities = level(N = 2, elevation = runif(n = N)),
    citizens = level(N = 2, elevation = runif(n = N)),
    cities = level(N = 3, elevation = runif(n = N))
  )
##   cities elevation.x citizens elevation.y
## 1      1   0.5728534        1   0.9446753
## 2      1   0.9082078        2   0.9446753
## 3      2   0.2016819        3   0.6607978
## 4      2   0.8983897        4   0.6607978
```

Not sure what the right behavior is, but not this!

**Comment by aaronrudkin** [comment]
I deal with data Ns not matching in issue #16, so allow me to consider the slightly simpler function call:
``
fabricate(
    cities = level(N = 2, elevation = runif(n = N)),
    citizens = level(N = 2, elevation = runif(n = N)),
    cities = level(N = 2, elevation = runif(n = N))
  )
``

We have three options for variable creation:
1. Variables can exist in multiple levels (some disambiguation required);
2. Variables can only exist on one level, and overwriting it on another level should error
3. Variables can only exist on one level and should never be overwritten.

1 seems ideal to me, but there are a few open questions: First, how do we keep a running tally of which variables exist at what level? Second, how do we disambiguate in terms of name? Third, if a user goes to overwrite the variable in the original level, how do we dynamically catch that the variable's name was changed during disambiguation, and change it?

So, in this example, fabricate might make the first level, creating a variable called elevation; then, when making the second level, rename elevation to elevation.cities, and create a variable called elevation.citizens; finally, when seeing elevation in the new cities level, do a lookup to confirm a variable called elevation was created on the cities level and have the sense to overwrite elevation.cities rather than creating a third variable called just elevation.

I actually don't think this would be too difficult. It would involve passing some additional data to level() -- a list mapping previously processed levels to variable names and a bit of fiddling with that list.

Alternatively, we might prefer to explicitly error so the user is absolutely sure they did not accidentally overwrite data across levels and so their variable names are not changed on the fly. This would also be easy to implement.

I agree that the current example behaviour seems obviously wrong.

**Comment by nfultz** [comment]
I think `citizens.elevation` is a bit more legible
(`cities.citizens.elevation` indicates nesting) , but then again, R has a
tradition of using suffixes in `merge()`.

**Comment by aaronrudkin** [comment]
I am going to close this because the rewrite of fabricate will moot it -- the end decision was to error if variable names are ambiguous (i.e. repeat names can only be used with modify_level operations.
