### ISSUE TITLE
Rewrite of Nesting / fabricate to support cross-classified data

### ISSUE THREAD

**Issue by nfultz** [DeclareDesign/fabricatr#23]
Right now, nesting is determined by position of levels in a single `fabricate` call, which means  `level()` has to pull double duty as both a generation 

Potential alternatives for expressing "students in schools":

  * Nesting via parenthesis: `schools = level(N_1, students=level(N_2, verbal=rnorm(), math=rnorm()))`
  * slashes: `schools = level(N_1) / student := level(N_2)` 
  * or the other way: `students = level(N_2) %nested_in% schools := level(N_1)`
 
Note the `:=` in there, we need a way to set names inside an exp instead of only using arg names. We could still allow the first one to be a `=` or we could make the `:=` required.

We could express cross classified designs similarly by defining `*` or perhaps `%cross%`

This would be a breaking change that would require us to fix many things, but it's probably better to figure it out now before we have a ton of users writing code against fabricatr.

**Comment by graemeblair** [comment]
Thanks, Neal. Don't mind breaking changes in this case for reasons you describe. Look forward to discussing tomorrow.

**Comment by aaronrudkin** [comment]
Graeme, Neal, and I met on this yesterday afternoon. The gist is that we'll be rewriting fabricate. We will not be adding operators, but there will now be three level functions: `add_level`, `nest_level`, and `modify_level`. fabricate will have a "working data frame". Nest_level will nest data into that data frame, add_level will lock any existing working data frame and put it in storage, create a new working data frame, and begin to build it. Modify_level will modify an existing level in the working data frame or stored data frames. Fabricate will return the final working data frame. This allows data to either be fully nested or partially nested, or cross-classified.

Neal had a pseudo-code user story that I will write up later in our new syntax, which boiled down to the following data structure (-> = nested in):
Primary Schools -> Primary Classes
Secondary Schools -> Secondary Classes
Students attached to both a primary class and a secondary class

We also expect not to break the existing level function so that users porting code from before now won't be hurt, although documentation will use add_level, nest_level, and modify_level.

I've renamed this issue and will hijack Neal's original post with progress notes rather than continuing to post comments.

**Comment by aaronrudkin** [comment]
As of the current commit, this is implemented in the fabricate_rewrite branch.

Example code (syntax not final):
```
df = fabricate(
  primary_schools = add_level(N = 100,
                              ps_quality = runif(n=N, 1, 100),
                              ps_hasband = draw_binary(0.5, N=N),
                              ps_testscores = ps_quality * 5 + rnorm(N, 30, 5),
                              ID_label = "PSID"),
  secondary_schools = add_level(N = 50, 
                                ss_quality = runif(n=N, 1, 100),
                                ss_hascomputers = draw_binary(ss_quality/100, N=N),
                                ss_testscores = ss_quality * 5 + rnorm(N, 30, 5),
                                ID_label = "SSID",
                                new_hierarchy = TRUE),
  students = cross_classify(N = 1000,
                            ps_quality,
                            ss_quality)
)
```

Notes:
- Because we got rid of `nest_level()`, we need syntax to tell `add_level()` that the level you want to add is a separate level hierarchy, not nested in the current level hierarchy. This syntax is ugly. I guess we can solve this by making a `new_level_hierarchy()` function, but I haven't yet.
- The `cross_classify()` function is super easy. Just specify N and the variables you wish to join on. Locating the variables in the hierarchies is handled transparently in the back.
- If you want correlated data, specify either `rho` (a scalar) or `sigma` (an NxN correlation matrix where N is the number of variables you're joining on) in the cross classify call:

```
df_correlated = fabricate(
  primary_schools = add_level(N = 100,
                              ps_quality = runif(n=N, 1, 100),
                              ps_hasband = draw_binary(0.5, N=N),
                              ps_testscores = ps_quality * 5 + rnorm(N, 30, 5),
                              ID_label = "PSID"),
  secondary_schools = add_level(N = 50, 
                                ss_quality = runif(n=N, 1, 100),
                                ss_hascomputers = draw_binary(ss_quality/100, N=N),
                                ss_testscores = ss_quality * 5 + rnorm(N, 30, 5),
                                ID_label = "SSID",
                                new_hierarchy = TRUE),
  students = cross_classify(N = 1000,
                            ps_quality,
                            ss_quality,
                            rho = 0.5)
)
```

Todo:
- Documentation
- Tests

Feedback?

**Comment by aaronrudkin** [comment]
Still need to document and test, but we now have the following syntax:
- `cross_level` for the initial call (pro: includes cross; includes level; is relatively succinct)
- `join` for an internal helper function to specify the nature of the join
- You can add variables after the cross-classify merge in the `cross_level` call.

Here is an example showing the newest syntax:
```
students = fabricate(
  primary_schools = add_level(N = 100,
                              ps_quality = runif(n=N, 1, 100),
                              ps_hasband = draw_binary(0.5, N=N),
                              ps_testscores = ps_quality * 5 + rnorm(N, 30, 5)),
  secondary_schools = add_level(N = 50, 
                                ss_quality = runif(n=N, 1, 100),
                                ss_hascomputers = draw_binary(ss_quality/100, N=N),
                                ss_testscores = ss_quality * 5 + rnorm(N, 30, 5),
                                nest = FALSE),
  students = cross_level(N = 1000,
                         by = join(ps_quality, ss_quality, rho=0.5),
                         student_score = ps_testscores * 5 + ss_testscores * 10 + rnorm(N, 10, 5),
                         student_score_2 = student_score * 2,
                         extracurricular = ps_hasband + ss_hascomputers
                         )
)
```
