### ISSUE TITLE
bootstrap speed

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#52]
Curious how our resample function compares to the bootstrap package or this: https://github.com/topepo/rsample in terms of speed, do we know?

**Comment by nfultz** [comment]
Tim Hesterbergs package is the best one for bootstrapping.

**Comment by graemeblair** [comment]
http://cran.fhcrc.org/web/packages/resample/

**Comment by aaronrudkin** [comment]
Heh, most of the other packages end up being specifically geared towards _doing_ something with the replicate -- not just generating the new data, so it's non-obvious how to do a fair benchmark. rsample will let me extract the intermediate data, while resample does not seem to have any provision for doing so.

```
library(fabricatr)
library(rsample)
library(ggplot2)
df = diamonds # 53,940 rows, 10 columns
microbenchmark(
  rsample = {
    out = rsample::bootstraps(df, times = 10)
    lapply(out$splits, function(x) { data.frame(x) })
  },
  us = {
    replicate(10,
              fabricatr::resample_data(df))
  }
)
```

Looks to me like we are 2-3% faster in the median case, could be noise, could be real.

I think this would be one of the harder functions to benchmark, since a N-unit single level bootstrap is, like, the least we can do, and most other packages can't do arbitrarily complex bootstraps. On the other hand, we're designed to make a single resampled replicate, while all the other packages are designed to do many replicates, but actually run a stat on them. So difficult to say what a more real world example would produce.

If anyone has an idea for a fairer benchmark between resample, rsample, and us, that'd be cool.

**Comment by aaronrudkin** [comment]
(I also uploaded this code in DDtools in case anyone wants to riff on it)

**Comment by graemeblair** [comment]
not sure what others think, but to me if in this simple case we are *as fast or faster* and we do other stuff - that's the right benchmark to use (which this seems to pass)

**Comment by aaronrudkin** [comment]
On the basis that we want to ship soon and our benchmark beats theirs, I'll close this. I would say it's probably worth revisiting later that other bootstrapping packages do the resample->replicate->stat->summary process in one pass, and whereas we have a comparative advantage on the resample step, we don't automate the other three.
