### ISSUE TITLE
Allow *_level to specify ID_Labels

### ISSUE THREAD

**Issue by nfultz** [DeclareDesign/fabricatr#74]
Currently, the only way to specify the level variable name is to set it as the parameter name from `fabricate()` - we should make these two equiv:

    fabricate(sleep, group=modify_level(m=1:2))
    fabricate(sleep, modify_level(m=1:2, ID_label="group"))

**Comment by aaronrudkin** [comment]
Note to others: this is a feature request designed to make something for DeclareDesign easier, not necessarily something public-facing for **fabricatr** users.

**Comment by aaronrudkin** [comment]
This is done and tested for the DD use case by @nfultz.

Things that changed are that we now have an alternate call form for this expression:
```
fabricate(my_level = add_level(N = 10))
```

Which looks like this:
```
fabricate(data = NULL, add_level(N = 10, ID_label = "my_level"))
```

My understanding from @nfultz is that the issue here is he has to inject the level name and NSE doesn't work properly on the left side of assignment without getting in to ugly hacks; and the other option would have been directly calling *_level and injecting an environment into it, which is also hacky and not what we want users to do. Anyway, all done and tests submitted to verify coverage.
